### ISSUE TITLE
can-event 3.0.0-pre.13 causes an infinite loop in can-define test

### ISSUE THREAD

**Issue by Sinjhin** [canjs/can-event#17]
PR #16 causes test "One event on getters (#1585)" to go into a loop at: https://github.com/canjs/can-define/blob/master/define-test.js#L710

**Comment by justinbmeyer** [comment]
I'm going to try to write this problem up the best I can.

`person.get` is called because `personId` changed in batch 1.

When `new Person()` is created, it:

1. tells `person.get` that it should care about `new Person().name` and `new Person().id`.
2. fires `name` and `id` events in the next batch (2).

The problem is that when `name` and `id` fire, the `person.get` compute will be re-evaluated again ... re-creating that person.

## Fixes 

The most simple fix, is to make creating a Person __not__ trigger events when being initialized.  

However, this might be short-sited.  It's possible other getters might call `Observation.add` AND trigger the same event.

We shouldn't be responding to those events.  We shouldn't be responding to any events triggered within the `person.get` read.

Computes already try to do this.  They use:

```
canBatch.afterPreviousEvents(this.setReady);
```

To make it so `dependencyChange` will do nothing until that time.

For some reason, this must not be working ....
